In [3]:
import numpy as nm  
import matplotlib.pyplot as mtp 
import seaborn as sns
import pandas as pd
data_set= pd.read_csv('2_result.csv')
data_set.head()

uuid  q1  q2  q3  q4  q5  q6  q7  q8  q9  \
0  397d4638-4f47-11eb-96cb-005056c00008   1   1   0   0   0   1   0   1   0   
1  3bef2ead-4f47-11eb-80fc-005056c00008   1   0   1   0   0   0   0   0   1   
2  3dd5cbe7-4f47-11eb-8f68-005056c00008   1   1   0   0   0   0   0   0   1   
3  4026c636-4f47-11eb-96c8-005056c00008   1   0   0   0   0   1   0   1   1   
4  424b9516-4f47-11eb-94af-005056c00008   0   0   0   0   1   0   1   1   1   

   ...  q31  q32  q33  q34  q35  q36  q37  q38  q39  res  
0  ...    0    1    0    1    0    0    1    1    0   17  
1  ...    0    0    1    1    1    0    0    0    1   17  
2  ...    0    0    0    1    1    0    1    1    0   12  
3  ...    1    1    1    1    1    1    1    0    1   15  
4  ...    1    1    0    0    1    1    1    0    1   16  

[5 rows x 41 columns]

In [4]:
data_set.shape

(5000, 41)

In [5]:
data_set.columns

Index(['uuid', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10',
       'q11', 'q12', 'q13', 'q14', 'q15', 'q16', 'q17', 'q18', 'q19', 'q20',
       'q21', 'q22', 'q23', 'q24', 'q25', 'q26', 'q27', 'q28', 'q29', 'q30',
       'q31', 'q32', 'q33', 'q34', 'q35', 'q36', 'q37', 'q38', 'q39', 'res'],
      dtype='object')

In [11]:
x=data_set.iloc[:,1:-1].values
y=data_set.iloc[:,-1].values
print(x)
print(y)

[[1 1 0 ... 1 1 0]
 [1 0 1 ... 0 0 1]
 [1 1 0 ... 1 1 0]
 ...
 [0 0 0 ... 1 0 1]
 [1 0 1 ... 1 0 0]
 [0 1 1 ... 1 0 1]]
[17 17 12 ... 17 16 18]


In [9]:
from sklearn.preprocessing import Binarizer
y = y.reshape(1, -1) 
binarizer=Binarizer(threshold=14).fit(y)
binaryy=binarizer.transform(y)
binaryy=binaryy.transpose()
binaryy.shape
y=binaryy
print(y)

[[1]
 [1]
 [0]
 ...
 [1]
 [1]
 [1]]


In [12]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
